<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DetailChannel;

class Detail_channelsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DetailChannel::insert([
            [
                'channel_id'           => 'UCor-ItevvphIaF0n8CkY-Xg',
                'title'      => 'おのだ/Onod',
                'description'          => '飛行機、ホテル、日本で生活する上でのお得情報をYouTubeで発信中。\n\nお金をあまり掛けずにマイル、クレジットカードなどを駆使して、ファーストクラス、ビジネスクラスに乗ったり、上級会員のステータスを獲得することについて日々、研究しています。LCC、安宿、変わった場所も大好きです。\n\n新卒で入ったNEC退職後、フリーランサーとしてブログとYouTubeの広告収入で生活。YouTubeチャンネル登録者は10万人以上、ブログは月間50〜100万PV。大阪在住、86年生まれ。\n\n韓国人の妻がおり定期的に韓国にもいっていますで、韓国についての紹介もよくしています。\n\nhttps://www.youtube.com/c/onodamasashi?sub_confirmation=1\n\nチャンネル登録をしていない人は是非ともお願いします。\n\nブログはほぼ毎日、更新しているのでチェックしてください。\n\n【ブログ：http://www.kankeri02.com/】\n\nまたTwitter、Instagramもやっており、この2つはリアルタイムなので私が今どこにいるかをチェックすることができます。\n\n【Twitter：https://twitter.com/kankeri02】\n\n【Instagram：https://www.instagram.com/kankeri02.bu】\n\nLINE@も月1ペースですが配信しています。大体、海外から発信するのでこちらもどうぞ！\n【LINE@:https://line.me/R/ti/p/%40kankeri02】\n\n妻のYouTubeチャンネル\nhttps://www.youtube.com/channel/UCIaWJ_tZO6Bv1SRb31qDE0Q?sub_confirmation=1\n\n問い合わせはこちら\nメールアドレス：onoda_team@kankeri02.com\n撮影にご協力いただいけるエアライン、ホテル、空港などの関係者の方、自治体さま等を常時募集しています。また個人の方でもレビューしてほしい飛行機の路線、場所など動画のネタになりそうなものがあれば教えて下さい!!\n※旅行などに関する個人的な質問はTwitterにお願いします。\n\n機内では他のお客さんにできるだけ迷惑にならないように音声マイクを利用して小声で話しています。',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLRBso7vHcqxzOtrTILlB3OaZoLQLT81usAHlu99OA=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2016-11-05T08:53:36Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => 'onodamasashi',
            ],
            [
                'channel_id'           => 'UC_Qg4a7T5w-rVbuTUy3RsZA',
                'title'      => 'おのだ Onoda',
                'description'          => 'メインチャンネルにあげるまでのない動画をこちらでアップしています。\n\n▼メインチャンネルはこちら▼\nhttps://www.youtube.com/c/onodamasashi',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLQ3tHjVWkLnoT0vmFX53CPiHL-4dGNgK2TR9aLcuA=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2017-12-28T10:45:40Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCxBR2bnAFAavDHpHtQrTA9Q',
                'title'      => 'スーツ 交通 / Suit Train',
                'description'          => '主にＪＲなど鉄道の解説動画を投稿しており、景色や沿線にある名所のご案内、座席の構造、特急列車の歴史、旧世代の産業遺産など対象はさまざまです。鉄道マニアの方が一番の客層だと思いますが、実際にはそれだけを相手にすると獲得できる数字に限界がありますので、なるべく一般の方に動画を見て頂けるように、平易な解説で鉄道マニアの世界を覗けるような動画制作を心掛けています。活動に際しては各鉄道会社のご迷惑にならないことを第一としています。内容は以前より正確性を期すようにしていますが、多数の動画を日々投稿する必要があるため、完全な状態からは程遠いものです。誤った情報が含まれている可能性に十分ご留意頂きたいと考えています。有益な補足や指摘のコメントにはハートマークをつけますので、動画の内容を補完するものとして注目してみてください。',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLSOrwEyt3krAwmQASrayjna6N8QW4BA65reZgXOPg=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2010-03-06T09:30:48Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '旅客鉄道会社を研究するチャンネル',
            ],
            [
                'channel_id'           => 'UCuDdJRJ6qR-wGILbpq-FXCw',
                'title'      => 'スーツ 旅行 / Suit Travel',
                'description'          => '鉄道を使い旅行する一連の流れをまとめてあり、視聴者に疑似的な旅行体験をしてもらうことを目標に動画を製作しています。多数の動画を投稿することを第一としているため、字幕、映像効果等はほぼ使用していません。また、予めお詫びいたしますが、事前に確認せず、うろ覚えの知識をそのまま喋るため、提供動画など特別の注意が必要とされるような動画を除いて、動画内で紹介している情報の1/3ぐらいが誤っています。これを訂正いただいた場合いいねボタンを押すようにしています。社会に悪影響を及ぼすような誤りがあった場合は削除します。ご旅行の参考になる情報は極力紹介しますが、ぜひそれが正しいかどうか、別途ご自身でお調べいただくことをお勧めいたします。',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLRGAKb-w7JuflHnTmzIh3lk-qoUAKCJp7-20NrKIQ=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2018-07-02T12:41:09Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UC2otzOMMLeJHZVwwyAQaA_w',
                'title'      => 'スーツ 背広チャンネル',
                'description'          => '参考になったコメント（論理的に説得力のあるもの、もしくは動画内で扱った内容に関する補足知識）には、私への好意の有無に関わらずいいね（ハート）を押しています）',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLTIsH_lLZHz1UFdH-QdEOZ5kZZhRqVKF77P5iCtWQ=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2016-12-21T03:46:32Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCTl3QQTvqHFjurroKxexy2Q',
                'title'      => 'Olympics',
                'description'          => 'Welcome to the Olympics YouTube channel, where the Games never end! 🥇\n\nFrom the best musical moments at the Olympic Games in our Music Monday series to weekly compilation videos with highlights from the Olympics on Fridays, plus exclusive documentaries about the stories behind the glory, this is where you can find everything about the biggest sporting event in the world.\n',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLRCFpu_biul8hGuPLuvU8l63Qmz4JLa0u8Pq_HarC0=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2006-01-10T17:22:11Z',
                'country'      => '',
                'defaultLanguage' => '',
                'customUrl' => 'olympics',
            ],
            [
                'channel_id'           => 'UCSOfXL-GmMHwlNFZVdaw5BA',
                'title'      => 'Olympic Tokyo 2020',
                'description'          => 'Welcome to Olympic Tokyo 2020\nChannel of the Olympic Games. Access breaking Tokyo 2020 news, plus records and video highlights from the best historic\n',
                'thumbnail'       => 'https://yt3.ggpht.com/8uvWSb8zcTEDGnMgG6whMWW8fqO_6rvEPRkoI8qB1FR1iRXdIgU1Ze6AAvdN7X_6mQnyAsk7sno=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2020-10-14T07:59:38Z',
                'country'      => '',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UC_kdjhHnkUbSImMrezjRyDQ',
                'title'      => 'Olympics Gymnastics',
                'description'          => 'Welcome to the official home of gymnastics at the Olympics. 🤸\n\nThis channel is dedicated to one thing and one thing only, the incredible sport of gymastics. Whether your are just getting into gymnastics, or you are a fully fledged member of the gymternet, you are in the right place to get your weekly fix of incredible gymnastics content.\n\n✅ Artistic Gymnastics\n✅ Rhythmic Gymnastics\n✅ Trampoline\n\nMake sure you subscribe and turn on notifications for our videos, so you don’t miss a thing!\n\n',
                'thumbnail'       => 'https://yt3.ggpht.com/9BBQQYxDDbr2tAGTV48jZpVjJKnC8JjXMdf05WViMeTHgVcCdAsZHCGnKUEB8nzXgsO5OO0i=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2021-06-15T12:38:23Z',
                'country'      => '',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCi8n36NkW2uCQSFZNiYtuMQ',
                'title'      => 'Paralympic Games',
                'description'          => "ParalympicSport.TV showcases sport like you have never seen it before. The International Paralympic Committe's online video channel streams live sport from Paralympic Games, World and Regional Championships, as well as uploading videos on demand from past events. Prepare to be inspired and excited by elite athletes with a disability showcasing their incredible sporting abilities. Subscibe free and be the first to watch great sporting action.\nOfficial website: http://www.paralympic.org",
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLTEkYslPaa2FsPP8ZKZ-1KPFmqVXgzLsDBTvXc3Fg=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2008-06-05T12:13:34Z',
                'country'      => 'DE',
                'defaultLanguage' => '',
                'customUrl' => 'paralympics',
            ],
            [
                'channel_id'           => 'UChAu4dQjR2vyR5baXOtMvVA',
                'title'      => 'Tokyo 2020',
                'description'          => '東京オリンピック・パラリンピック競技大会組織委員会 YouTube公式チャンネルです。\n東京2020大会開催に向けて様々な情報を紹介いたします。\nWelcome to the Official Channel of The Tokyo Organising Committee of the Olympic and Paralympic Games.\n',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLQBeYLW4Vr_XrXCAmMuVpwGp882AqM2jIHQRjaaeA=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2015-09-02T05:51:28Z',
                'country'      => 'JP',
                'defaultLanguage' => 'ja',
                'customUrl' => 'tokyo2020',
            ],
            [
                'channel_id'           => 'UCxs4TtlgxC7Nda6jEJF6Ejg',
                'title'      => 'ヒロシの時事ニュースチャンネル',
                'description'          => '主にニュース記事などを読みながら自分なりの頭の悪い意見を述べさせていただいております。生暖かい目で見守っていただけると嬉しいです。\ntwitterもやっているのでぜひフォローしてくださいね。\nhttps://twitter.com/youtube82738016\n\n【サブ垢】ヒロシのプライベートチャンネル\nhttps://www.youtube.com/channel/UCbajpFNYPYj7Kg0S3gaBzUA\n\n※何かございましたら、TwitterのDMよりお願いいたします。\n',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLTMYGCSfIWPHoMQFlBIUZas7_jzt1fwewqtxJY=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2019-01-31T06:49:14Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCbajpFNYPYj7Kg0S3gaBzUA',
                'title'      => 'ヒロシのプライベートチャンネル',
                'description'          => 'ヒロシの時事ニュースチャンネルのサブ垢です。時事ニュース以外のヒロシのプライベートや身辺に起こった突発的な事件などを配信していきたいと思います。\nみんなでワイワイやりたいです。よろしくね。\n\n※何かございましたら、TwitterのDMよりお願いいたします。\n',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLRyaKQOqDXphc6AZ1d2ca__guL7s1YPa-OHBlmJ=s88-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2020-06-14T10:55:47Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCayCSFEFS_7YQViPjGJiwSA',
                'title'      => '失敗小僧',
                'description'          => 'コラボについては　ユーチューブチャンネルをお持ちで顔出しをされている方（登録者数不問）　士業の方　建設業許可や宅建業許可をお持ちの方　飲食店（移動販売やケータリングのみを含む）を経営されている方  店舗型小売り業を経営されている方　などの方に限定させていただいております。まずは　概要欄にある連絡先のメールあてにご一報いただければと思います　そのうえで　コラボ可能かについてお打ち合わせさせていただきます。\n',
                'thumbnail'       => 'https://yt3.ggpht.com/kq7p4ZRa2vcpWLrogBzbAgFM1bfhF9tbi5LMIvAoWyjTJNzKgLZAUb4xKS9TuOA5lqo89w_hgfg=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2018-11-06T13:08:00Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UC_Q8cHoJnhNp6GHPkPOoSgw',
                'title'      => '一月万冊',
                'description'          => '一月万冊　清水有高　月1,500〜3,000冊の読書をする読書家\n質問受け付けメルアド　shimizu@raku-job.jp　氏名と所属を記入してメールヨロシク！\n\nこの動画は\nアニメゲームマンガ専門求人サイト　ラクジョブ\nアニメゲームマンガ専門営業コンサル　ラクビジ\nを提供しているビ・ハイア株式会社の代表取締役でありコーチや投資家としても活動している清水有高が読書家としての活動を動画にアップしています。\n\n一月万冊　1ヶ月で1万冊読めたらいいな！\nhttps://www.facebook.com/monthlymansatsu\n\nのFacebookページを運営し、一月1,500〜3,000冊の読書を実践している清水有高の読書動画です。\n\nビ・ハイア株式会社 代表取締役社長 清水有高\nアニメゲームマンガ専門求人サイトラクジョブ\nhttp://raku-job.jp\n一月万冊　1ヶ月で1万冊読めたらいいな！\nhttps://www.facebook.com/monthlymansatsu\n〒104-0061　東京都中央区銀座5-15-1南海東京ビルSP263\ntel&fax : 03-5953-8795 fax 03-5953-8862',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLQ-CtYUfsnj4MQxuJ1ZmsRe3fYaKgFjWQ-L2d_1nA=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2014-01-12T09:33:35Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => 'yukoreadman',
            ],
            [
                'channel_id'           => 'UC7I3QTra4_kC4TSu8f7rHkA',
                'title'      => 'マコなり社長',
                'description'          => '人生を変える機会になる話を配信します。\nチャンネル登録よろしくおねがいします！\n\nこれから「もっと活躍したい！」と思っているビジネスパーソン・学生の方に特におすすめです。\n\n本業は、渋谷で教育事業を運営する株式会社divの社長です。\n\n22歳で起業してこれまで成功ばかりではありませんでした。\n事業は撤退、借金を背負い、仲間もみんな辞めたこともあります。\n\nでも、失敗した分だけ、人一倍多くのことを学ぶことができました。\n\n私の経験・知見を多くの人に還元したいと思いYouTubeをはじめました。\nこれまで知らなかったハウツー・思考法を知って成功体験を得ていただきたいと思っています。\n\nもちろん私も完全な人間ではありません。\nみなさんと一緒に学びあい、成長していけるとうれしいです。\n\n■【集大成】オンラインビジネススクールUNCOMMON\nhttps://un-common.jp/\n↑思考力を中心としたビジネススキルが身につきます\n\n■【実績No.1/日本最大級】テックキャンプ エンジニア転職\nhttps://tech-camp.in/expert \n↑完全オンラインで挫折せず学べます\n\n\n【マコなり社長のプロフィール】\n■本名\n真子就有(まこゆきなり)\n\n■生年月日\n1989/9/18\n\n■所属\n株式会社div 代表取締役/ Founder\n\n■趣味\nバスケ/アニメ/映画\n\n■会社のコーポレートサイト\nhttps://di-v.co.jp/\n\n■YouTubeビジネス関係のお問い合わせ（企業案件・コラボ等）\nhttps://forms.gle/YWXVuj9KrCKAB5ZE9\n\n■動画制作\n原稿：マコなり社長\nアートディレクション：堀井拓也  https://twitter.com/holy_1008\n編集・サムネイル：マコなり社長監修のもとスタッフが作成',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLS7Ucx7Kd1dH6aD91ByjteqnEaJP9y1MGcQNg9E=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2018-11-21T07:52:49Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCFdBehO71GQaIom4WfVeGSw',
                'title'      => 'メンタリスト DaiGo',
                'description'          => '⭕️DaiGoの心理学動画が無料で見放題⭕️\n 【Dラボ】は下の青いDラボ🐈\u200d⬛のアイコンから20日間無料\n\n【免責事項】\nこのチャンネルは、科学の面白さを伝えることを目的としたエンタメです。\n\nなるべく多くの方に、科学的思考に興味を持ってもらうために、参考資料や過去の動画を元に、大胆な独自の考察したもので、事実を確定するものではなく、あくまで一説です。動画の結論は実際の研究とは異なる場合があります。\n\n僕は文献を読むのが好きなタダの理系であり、専門家ではありません。また、多くの科学者とも同じように人間ですから、間違うことも多々あります。実際に知識を利用する際には自己責任、または然るべき専門家に相談してください。また、Amazonリンクはアソシエイトリンクを使用しております。\n\nメンタリストDaiGoの心理学動画が見放題の 【Dラボ】は\n⬇️ここから20日間無料',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLRAiHA_r6zKPUGcedHXsjU451VP4PIQVDYLjqvkLg=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2013-01-03T14:05:32Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => 'mentalistdaigo',
            ],
            [
                'channel_id'           => 'UC0yQ2h4gQXmVUFWZSqlMVOA',
                'title'      => 'ひろゆき, hiroyuki',
                'description'          => 'Howdy?',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLTPvI7i2VZ52nrseXhIQSDskPlq1eGKsHBSjqZm=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2016-01-30T22:16:05Z',
                'country'      => 'FR',
                'defaultLanguage' => '',
                'customUrl' => 'hiroyukix',
            ],
            [
                'channel_id'           => 'UCsdpSVn4s0eAhlV144a8lGA',
                'title'      => 'はりーの仕事塾',
                'description'          => 'はじめまして。\n元銀行員、元転職エージェントのはりーです。\n\n「はりーの仕事塾」とは\n大人が本気で学び続ける場所です。\n\n常識を疑い、日本国民の人生観、仕事観、及び資産形成に役立つ情報を発信し続けます。\n\nはりーと一緒に学びたい方は、ぜひチャンネル登録の上、入塾願います！\n\n↓【有料メンバーシップはこちらから】\nhttps://www.youtube.com/channel/UCsdpSVn4s0eAhlV144a8lGA/join\n\n\n【活動の足跡】\n2019年12月　YouTube動画初投稿\n2020年1月　　チャンネル登録者100人\n2020年2月　　チャンネル登録者1000人\n2020年3月　　チャンネル登録者1万人(3ヶ月)\n2020年8月　　チャンネル登録者3万人\n2020年9月　　チャンネル登録者4万人\n2020年12月　  チャンネル登録者5万人達成（1年）\n\nTwitter:  https://twitter.com/haaary1012\nInstagram: https://www.instagram.com/haaa_ry\n\n【経歴】\n28歳。富山県出身。\n立命館大学法学部卒。\n新卒で銀行に入行し、法人融資業務などを約2年間経験。\nその後、転職エージェントを経て現在に至る。\n2019年12月12日にYoutubeデビュー。\n\n',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLTjwwceOX0ORZxdO7oZ0gen8sAV2TiKJowzL_2PfQ=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2012-06-14T13:24:01Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCSPEjw8F2nQDtmUKPFNF7_A',
                'title'      => 'NHK WORLD-JAPAN',
                'description'          => "NHK WORLD -JAPAN is the international broadcast service of NHK, Japan's sole and one of the biggest public broadcasters in the world. NHK WORLD-JAPAN provides latest information and a wide variety of programming on Japan, Asia and the rest of the world 24 hours a day. Here you will find trailers of our recommended programmes. \n\nFor more visit our website\n https://www3.nhk.or.jp/nhkworld/",
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLQ9ItuDialCNXYh2ue_wnjMND6mh3JIWPLfDprFZw=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2007-03-11T09:01:54Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => 'nhkworldjapan',
            ],
            [
                'channel_id'           => 'UC5mluA5iLPDoQAZuXTGE6MA',
                'title'      => '代ゼミ仲本浩喜 なっかんチャンネル',
                'description'          => '',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLRiAf2aoc1wcRIADWAO0E2YPRfmP-KDwqoo2LCI=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2020-03-29T16:43:22Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCd2xXtqLIXEy8v47zaA5gkA',
                'title'      => '西きょうじ',
                'description'          => '西きょうじによるポレポレYouTubeチャンネル。https://www.youtube.com/c/西きょうじポレポレ\nポレポレ英文読解講義　https://www.youtube.com/playlist?list=PLTVJQzNVadQf-Ghy4JAz5PZgz-_QhaeIu\n西きょうじのYouTubeのチャンネル登録はこちら！\nhttps://www.youtube.com/channel/UCd2xXtqLIXEy8v47zaA5g\n\n著書「ポレポレ英文読解プロセス50」などの参考書以外に「踊らされるな自ら踊れ」「仕事のエッセンス」「そもそも」「越境へ」（津田大介氏との共著）「さよなら自己責任」など多数。\n\n西きょうじのTwitter \nhttps://twitter.com/kyojinishi\n\n【西きょうじ著書一覧】\nhttps://www.amazon.co.jp/s?k=西きょうじ&__mk_ja_JP=カタカナ&ref=nb_sb_noss',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLQEuLKFNiXPTeoFmNklH-4OeCWLAEUcVp0Az13-=s240-c-k-c0xffffffff-no-rj-mo',
                'published'       => '2019-11-19T14:21:59Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '西きょうしホレホレ'
            ],
            [
                'channel_id'           => 'UCjFLByL3JGp7qwGSV4zoQNA',
                'title'      => '関西弁CA / Ryucrew',
                'description'          => '【関西CA / Ryucrew】\n\n大阪出身、なにわ育ち、現在バンクーバー在住で男性CA(客室乗務員)のRyucrewです。\n\n日本でもとっても短い間、客室乗務員として働いていましたが、\nその甲斐もなく関西弁(大阪弁)は抜けず、\nというか直す気なしで、これまでやってまいりました。\n（でもエセ標準語で頑張っている動画もあります）\n\nおしゃれな動画をアップしようと始めたYouTubeですが、\nこれからは飾らずありのままをシェアしようと思います。笑\n\n\n一応、私の趣味でやっていることですので、\n乗務している会社やその詳細は伏せさせてくださいね。すみません。\n\n\n今住んでいるカナダのこと、バンクーバーのこと、\n仕事のこと、暮らしのこと、思いつきで動画作りしていきます。\n\nどうぞよろしくお願いします！\n\n\n2021年1月15日よりサブチャンネル\n【RYUCREW ASMR】を始めました！\n関西弁男子(僕自身です。笑)のASMR専門チャンネルです、よければ覗いて頂ければ幸いです！\n↓\nhttps://www.youtube.com/channel/UCkSymrqF-AFupVTZ0m1tz5g\n\n\n【Instagram / インスタグラム】\nryucrew_vancouver\n\n【PO Box address / お手紙などの宛先(カナダ)】\nPO Box 36557 SEAFAIR\nRICHMOND BC CANADA \nV7C 1V0\n\n\n#カナダ　#バンクーバー　#客室乗務員　#男性CA　#男性客室乗務員　#クルー\n#キャビンアテンダント　#カナダ　#バンクーバー　#客室乗務員　#男性CA　#キャビンアテンダント\n#フライトアテンダント　#海外生活　#外資系CA　#関西弁CA　#関西弁　#関西人\n#大阪弁　#大阪人',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLSwi_o4hwrLMa237obOW5C9E3OPspNIQ8Wvho6h=s240-c-k-c0x00ffffff-no-rj',
                'published'       => '2020-05-15T02:05:20.041185Z',
                'country'      => 'CA',
                'defaultLanguage' => '',
                'customUrl' => 'ryucrew',
            ],
            [
                'channel_id'           => 'UCa2pKVpcK8KsrnYJH64Ah1g',
                'title'      => '双子CAさくらん - FlyTwins SakuRan',
                'description'          => 'アメリカで客室乗務員として働いている双子です😊😊\n\n・CAの仕事\n・海外生活\n・外資系企業での働き方\n・双子トピック\n\nなどを動画にまとめて更新していきます。\n宜しくお願いします♪\n\n\n\n【Instagramもやってます！】\n　▷さく　@sakudayo_\nhttps://instagram.com/sakudayo_\n　▷らん　@ran_dayo\nhttps://instagram.com/ran_dayo',
                'thumbnail'       => 'https://yt3.ggpht.com/pX24mVJ6rBu7yO63xfbEJm7IXb-XVbZnvxZY-_EWkt-GWJrgqhuzEUM3HLdJTxkYKKJwMNNoGQ=s240-c-k-c0x00ffffff-no-rj',
                'published'       => '2020-07-22T18:14:35.418017Z',
                'country'      => 'US',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCE0TGi9KCzSxNUX-uR13h_A',
                'title'      => 'theflyingstewardチャンネル',
                'description'          => 'みなさん、こんにちは！\n私は現在アメリカ・コロラド州のデンバー在住のMoriakiです。\n東京出身の30代後半で、渡米歴20年になります。現在はニューヨークを拠点として客室乗務員/キャビンアテンダントとして飛んでいます。\n\n男性CAの視点から客室乗務員に関する動画やアメリカ生活・LGBTカップル動画をvlog形式でご紹介しています。チャンネル登録もよろしくお願いします！\n\n************************************\n【公式サイト】\nIG: instagram.com/theflyingsteward\nFb: facebook.com/theflyingsteward\nYouTube: youtube.com/c/theflyingsteward\n*************************************\n【企業案件及びコラボ案件】\n連絡先: theflyingsteward@outlook.com\n*************************************\n【お便り・ラブレターもお待ちしてます！】\nMoriaki - theflyingsteward\nPO Box 471371\nAurora, CO 80047 USA\n*************************************\n【楽曲提供 / Music and Sound Effects】\nEpidemic Sound: www.epidemicsound.com\n*************************************\nDisclaimer:\nOpinions expressed are solely my own and do not express the views of opinions of my employer.',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLTFQgCBTZoRluaoX4FrRXIea6j92rGNEvDu7jVp=s240-c-k-c0x00ffffff-no-rj',
                'published'       => '2007-04-18T03:54:27Z',
                'country'      => 'US',
                'defaultLanguage' => '',
                'customUrl' => 'theflyingsteward',
            ],
            [
                'channel_id'           => 'UCXcjvt8cOfwtcqaMeE7-hqA',
                'title'      => 'SUSURU TV',
                'description'          => 'ずるずる、どうもSUSURUです！\n「毎日ラーメン健康生活」をテーマに、ラーメンをすする動画を毎日18:30に配信しています。\n日々ラーメンをすすり続け、現在2000日以上連続配信中です！\n全国の美味しいラーメンをすすりたい、紹介したいという気持ちで毎日続けておりますので\n宜しければチャンネル登録よろしくお願いします！\n\n生粋のラーメンYouTuber、SUSURUによる\n「毎日ラーメン健康生活」を追うチャンネル。\n\n「毎日ラーメン健康生活」とは\nラーメン大好きSUSURUが毎日ラーメンを食べても健康でいれることを証明していく生活。\n現在2000日以上、毎日ラーメンをすすり続けている。\n\n日本全国のラーメンをすする為、ラーメン図鑑としてもお使いいただけます。\n都道府県別再生リストや、二郎系ラーメン、家系ラーメン、といったジャンル別再生リストもございますのでご活用ください！\n世界のRamenも追っていきたい！！\n\n----------------------------------------------\n■twitter\nhttps://twitter.com/susuru_tv\n\u200b\n■instagram\nhttps://www.instagram.com/susuru_tv/\n\u200b\n★SUSURU TV.の公式グッズサイト★\nhttps://susurutv.stores.jp/\n\nお仕事依頼やお問い合わせ等は以下のアドレスまで！\ninfo@susurulab.co.jp\n----------------------------------------------\n',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLSmdVKAKiYJYtvSR38X0UAnLwviAg4olRbrHtCtFw=s240-c-k-c0x00ffffff-no-rj',
                'published'       => '2015-11-02T02:05:56Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => 'susurutv',
            ],
            [
                'channel_id'           => 'UCVdjYnmDsyiUcpcryI-k6ZA',
                'title'      => 'SUSURUのミッドナイトTV',
                'description'          => '説明\n毎日ラーメン健康生活をしているYouTuber  SUSURUのサブチャンネルです。\n\n深夜っぽい感じの、なんかゆるっとした企画をモヤっとやっていく。月１でどこかでツアーをします。\n\nメインチャンネルSUSURU TV.では今日も明日もラーメンすすってます。\nhttps://www.youtube.com/c/SUSURUTV\n\nこちらのサブチャンネルではSUSURU TV.を一緒に作っている\nチャル蔵(撮影部屋の家主及び編集その他担当)、ノビー(編集担当、顔出し無し）も登場します。\n\n業務連絡は\ninfo@susurulab.co.jp\nまで！',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLQLpOKRFaHwWxSMEAnnu93-pCCJ03e_dJnIMLXR=s240-c-k-c0x00ffffff-no-rj',
                'published'       => '2016-11-08T07:08:39Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
            [
                'channel_id'           => 'UCenJoA0xnqVKrhyOnVrCtOQ',
                'title'      => 'ロイドごはん',
                'description'          => '『フラメンコロイド』というバンド３人組が\n各地で出会ったグルメを毎日お届けしてます！\n\n2017年6月23日始動！\n2018年6月9日登録者1000人突破！\n2019年1月27日10000人\n2019年6月30日50000人\n2020年9月27日100000人\n2021年2月25日140000人\n★2010年から旅を開始現在は日本9周目！\n\n登録＆高評価！応援よろしくお願いします！\n\n——————【メンバー紹介】——————\n\n★メロンシート（G）★あや（Vo）★まこ（Per＆Vo）\n\n———《姉妹チャンネル》———\nメロンシート ジャーニー https://www.youtube.com/channel/UCwNlBAUziFWkJZFY_u3t65A\nフラメンコロイド https://www.youtube.com/channel/UCsFJHNg3SR41R2a3vctUInw\n\n—————《twitter》—————\nロイドごはん https://twitter.com/roidgohan\nメロンシート https://twitter.com/meloncito310\nフラメンコロイド  https://twitter.com/flamenkoroid\n\n—————《インスタ》—————\nロイドごはん https:/https://www.amazon.co.jp/ナイ/www.instagram.com/roidgohan \nメロンシート https://www.instagram.com/satoshimelo...\nフラメンコロイド  https://www.instagram.com/flamenkoroid\n\n—————《HP》—————\nロイドごはんの公式ブログ https://ramenjapan.net/\nメロンシート ジャーニー https://pordiotama3.xsrv.jp\nフラメンコロイドの神話と伝説 https://flamenkoroid.net\n\n【お仕事のご依頼】\nhttps://www.uuum.co.jp/inquiry_promotion\n\n【お手紙・プレゼント】\n〒107-6228\n東京都港区赤坂9-7-1\nミッドタウン・タワー 28階\nUUUM株式会社ロイドごはん宛',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLRxqOVlncdN0TDuBHYTDRCq0lVXQilksdOqUvjE5g=s240-c-k-c0x00ffffff-no-rj',
                'published'       => '2016-05-28T08:44:56Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => 'ロイトこはん',
            ],
            [
                'channel_id'           => 'UCvF9_9I_6tfl0NmXN0yS1Kw',
                'title'      => 'わっきーTV/石脇誠【全国グルメ動画チャンネル】',
                'description'          => 'わっきーこと石脇誠のわっきーTVへようこそ。\nこのチャンネルでは、様々な飲食店・チェーン店新メニューなどを紹介しています。\nご当地グルメやホテル、観光なども不定期で紹介しています。\n\n▷わっきーの各SNS＠フォローよろしく！\n★Twitter → https://twitter.com/makoto_ishiwaki\n★Instagram → https://instagram.com/makoto_ishiwaki/\n★FaceBook → https://www.facebook.com/wackytv/\nわっきーTVを見てお店に行かれた方で、SNS投稿される際は、\n#わっきーTV をつけて投稿してもらえると嬉しいです！\n\n▷わっきーTVのLINEスタンプ絶賛発売中！\nhttps://store.line.me/stickershop/product/9817845/ja\n\n▷業務連絡はこちら\nwackytv.off@gmail.com\n\n▷お仕事や地域活性化/観光/ご当地グルメ紹介に関してはこちら\n〒170-0005\n東京都豊島区南大塚2-25-15South新大塚ビル12F\nまちレポ株式会社\ninfo@machirepo.co.jp\n\n▷お手紙や贈り物はこちら\n〒150-0041\n東京都渋谷区神南1-20-9 ABC-MART公園通りビル5F\n株式会社ニュースタッフプロダクション わっきーTV宛\nhttp://www.newstaffpro.com/\n※ナマモノ等はご遠慮下さい\n\n※楽しくご視聴いただいている方々が不快に思うコメントは、削除、ブロックさせていただいています。\nまた、コメントはNGワードもありますので、引っかかると反映されない事があります、ご了承ください。',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLTiUcvPzpufOVXryV_EeGJiA2Ix1Z9OIbQgiXdlxg=s240-c-k-c0x00ffffff-no-rj',
                'published'       => '2015-01-17T02:07:21Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => 'wackytv01',
            ],
            [
                'channel_id'           => 'UCUwN_6mAGFYNkaTh9fKeXpg',
                'title'      => 'アカボシマシマシTV',
                'description'          => 'アカボシです\nラーメン二郎と二郎系を食べるのが好きなのであります。\n2日に一回くらい更新！\n19時くらいに更新！\n\nTwitter\nhttps://twitter.com/urawa_seijin',
                'thumbnail'       => 'https://yt3.ggpht.com/ytc/AKedOLQ6e7xVRPpvBQueXvnfpVBxIJghlIASScMysGJE2g=s240-c-k-c0x00ffffff-no-rj',
                'published'       => '2016-06-28T12:51:13Z',
                'country'      => 'JP',
                'defaultLanguage' => '',
                'customUrl' => '',
            ],
        ]);
    }
}
